name: GitHub Repo Creation Request
title: "[Create GitHub Repo]: "
body:
  - type: input
    id: repo-name
    attributes:
      label: GitHub Repo Name
      desription: Please provide GitHub Repo Name
      placeholder: ex. sdp-test-repo-name
  - type: input
    id: team-name
    attributes:
      label: Team Name in Org
      desription: Provide your team's name in Org which will own this repo
      placeholder: ex. devops-enablement
