name: GitHub Repo Creation Request
description: Repo Creation Form
title: "[Create GitHub Repo]: "
body:
  - type: input
    id: repo-name
    attributes:
      label: GitHub Repo Name
      description: Please provide GitHub Repo Name!
      placeholder: ex. sdp-test-repo-name
  - type: input
    id: team-name
    attributes:
      label: Team Name in Org
      description: Provide your team name in Org which will own this repo!
      placeholder: ex. devops-enablement
  - type: input
    id: apm-number
    attributes:
      label: APM Number for the Application
      description: Provide AP Number for your Application
      placeholder: ex. APM00123
