name: GitHub Repo Creation

on:
  issues:
    types:
      - opened

jobs:
  github-repo-create:
    name: Create github repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/REPO-CREATE.yaml
      
      - run: cat ${HOME}/issue-parser-result.json
      - run: |
          repo_name=`jq '."repo-name"' ${HOME}/issue-parser-result.json`
          team_name=`jq '."team-name"' ${HOME}/issue-parser-result.json`
          echo $repo_name $team_name
          echo $repo_name >> $GITHUB_ENV
          echo $team_name >> $GITHUB_ENV
          which cookiecutter
           
