name: GitHub Repo Creation

on:
  issues:
    types:
      - opened

jobs:
  github-repo-create:
    name: Create github repo
    runs-on: ubuntu-latest
    env:
        BODY: ${{ github.event.issue.body }}
        BODY1: "$(jq '.issue.body' $GITHUB_EVENT_PATH)"
    steps:
      - uses: actions/checkout@v3

      - name: Print issue body
        run: echo "${BODY}"
      - name: Print another
        run: echo "{BODY1}"
           
