name: GitHub Repo Creation

on:
  issues:
    types:
      - opened

jobs:
  github-repo-create:
    name: Create github repo
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/REPO-CREATE.yaml
      
      - run: cat ${HOME}/issue-parser-result.json
      - run: |
          repo_name=`jq -r '."repo-name"' ${HOME}/issue-parser-result.json`
          team_name=`jq -r '."team-name"' ${HOME}/issue-parser-result.json`
          echo "repo_name=$repo_name" >> $GITHUB_ENV
          echo "team_name=$team_name" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: "GauJosh/cookiecutter-template"
          token: ${{ secrets.PAT }}
          path: "template"
      - name: list files
        run: |
          cd template
          python -m pip install --user cookiecutter
          cookiecutter https://GauJosh:"${PAT}"@github.com/GauJosh/cookiecutter-template --no-input repo_name=$repo_name team_name=$team_name
      - name: Push new repo
        run: |
           pwd
           cd template/"${repo_name}"
           git init
           git add .
           git commit -m "Initial Commit"
           gh repo create GauJosh/"${repo_name}" --source=. --private --push
           
